#pragma once

#include "def.h"

/// @file
/// <summary>
/// Contains basic gdi3d core functions that are commonly used throughout an application.
/// </summary>

/// <summary>
/// Initializes all resources required by gdi3d. <para/>
/// It is required to call this function before any other gdi3d call in the application.
/// </summary>
/// <returns>A boolean value indicating that the initialization succeeded.</returns>
extern GDI3DAPI BOOL GDI3D_Initialize(VOID);

/// <summary>
/// Finds at runtime whether SSE2 instructions are available on the machine or not.
/// </summary>
/// <returns>A boolean value indicating that the SSE2 instruction set is present.</returns>
extern GDI3DAPI BOOL GDI3D_IsSse2Present(VOID);

/// <summary>
/// Finds at runtime whether AVX2 instructions are available on the machine or not.
/// </summary>
/// <returns>A boolean value indicating that the AVX2 instruction set is present.</returns>
extern GDI3DAPI BOOL GDI3D_IsAvx2Present(VOID);

/// <summary>
/// Queries the system's performance counter for the amount of time that has passed.
/// </summary>
/// <returns>An unsigned 64-bit integer value set to the time in microseconds.</returns>
extern GDI3DAPI DWORD64 GDI3D_QueryMicroseconds64(VOID);

/// <summary>
/// Queries the system's performance counter for the amount of time that has passed.
/// </summary>
/// <returns>An unsigned 32-bit integer value set to the time in microseconds.</returns>
extern GDI3DAPI DWORD GDI3D_QueryMicroseconds(VOID);

/// <summary>
/// Queries the system's performance counter for the amount of time that has passed.
/// </summary>
/// <returns>An unsigned 64-bit integer value set to the time in milliseconds.</returns>
extern GDI3DAPI DWORD64 GDI3D_QueryMilliseconds64(VOID);

/// <summary>
/// Queries the system's performance counter for the amount of time that has passed.
/// </summary>
/// <returns>An unsigned 32-bit integer value set to the time in milliseconds.</returns>
extern GDI3DAPI DWORD GDI3D_QueryMilliseconds(VOID);

/// <summary>Retrieves the last gdi3d error code generated by any of the gdi3d APIs.</summary>
/// <remarks>
/// This function is thread-safe, meaning you can use it from any concurrent thread in your
/// application without risking race conditions. <para/>
/// To know when to use this function, you should check any values returned by a gdi3d function
/// for NULL if it returns a pointer, 0 if it returns an integer or FALSE if it returns a boolean.
/// </remarks>
/// <returns>A gdi3d error code in the <see cref="GDI3D_ERROR" /> enumeration.</returns>
extern GDI3DAPI GDI3D_ERROR GDI3D_GetLastError(VOID);

/// <summary>Retrieves the last Direct3D 9 HRESULT code.</summary>
/// <remarks>
/// This function is thread-safe, meaning you can use it from any concurrent thread in your
/// application without risking race conditions. <para/>
/// To know when to use this function, you should check any values returned by a gdi3d function
/// for NULL if it returns a pointer, 0 if it returns an integer or FALSE if it returns a boolean.
/// </remarks>
/// <returns>
/// An HRESULT code that can be compared against the D3DERR and D3DXERR enumerations.
/// </returns>
extern GDI3DAPI HRESULT GDI3D_GetLastD3D9Result(VOID);

/// <summary>
/// Destroys all resources managed by gdi3d. <para/>
/// Only call when gdi3d is no longer used by the application. <para/>
/// </summary>
/// <remarks>
/// This function does not set a last error.
/// Whenever it fails, it is assumed that the thread local storage failed to be freed.
/// </remarks>
/// <returns>A boolean value indicating that the initialization succeeded.</returns>
extern GDI3DAPI BOOL GDI3D_Destroy(VOID);